-- SecurityLens schema. Idempotent: safe to run on every boot.
--
-- The logs table becomes a TimescaleDB hypertable when the extension is
-- available and stays a plain table otherwise; every query in the codebase
-- is written to work either way.

CREATE TABLE IF NOT EXISTS logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts          TIMESTAMPTZ NOT NULL,
    source      TEXT NOT NULL,
    event_type  TEXT NOT NULL,
    username    TEXT NOT NULL DEFAULT '',
    src_ip      TEXT NOT NULL DEFAULT '',
    dst_host    TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT '',
    bytes_out   BIGINT NOT NULL DEFAULT 0,
    message     TEXT NOT NULL DEFAULT '',
    extra       JSONB,
    -- Ground-truth labels: written by the seeder, read ONLY by cmd/eval and
    -- tests. Detector code never selects these columns (enforced by
    -- `make check-label-firewall`).
    attack_id   TEXT NOT NULL DEFAULT '',
    attack_type TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (id, ts)
);

-- Hypertable when TimescaleDB is present; NOTICE + plain table otherwise.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
        PERFORM public.create_hypertable('logs', 'ts', if_not_exists => TRUE, migrate_data => TRUE);
    ELSE
        RAISE NOTICE 'timescaledb extension not installed; logs remains a plain table';
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_logs_ts        ON logs (ts);
CREATE INDEX IF NOT EXISTS idx_logs_user_ts   ON logs (username, ts);
CREATE INDEX IF NOT EXISTS idx_logs_srcip_ts  ON logs (src_ip, ts);

-- Ground-truth attack manifest (evaluation only; see label firewall note).
CREATE TABLE IF NOT EXISTS attacks (
    attack_id   TEXT PRIMARY KEY,
    attack_type TEXT NOT NULL,
    entity      TEXT NOT NULL,          -- primary entity: username or src IP
    ts_start    TIMESTAMPTZ NOT NULL,
    ts_end      TIMESTAMPTZ NOT NULL,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS alerts (
    id           UUID PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    alert_type   TEXT NOT NULL,
    severity     TEXT NOT NULL,
    entity       TEXT NOT NULL,
    username     TEXT NOT NULL DEFAULT '',
    src_ip       TEXT NOT NULL DEFAULT '',
    title        TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'open',
    count        INT NOT NULL DEFAULT 1,
    window_start TIMESTAMPTZ NOT NULL,   -- event-time span of the evidence
    window_end   TIMESTAMPTZ NOT NULL,
    dedup_key    TEXT NOT NULL UNIQUE,
    evidence     JSONB,
    triage       JSONB,
    incident_id  UUID
);

CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_entity  ON alerts (alert_type, entity);

CREATE TABLE IF NOT EXISTS incidents (
    id          UUID PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    entity      TEXT NOT NULL,
    title       TEXT NOT NULL,
    severity    TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'open',
    alert_count INT NOT NULL DEFAULT 0,
    first_seen  TIMESTAMPTZ NOT NULL,
    last_seen   TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS llm_usage (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            TIMESTAMPTZ NOT NULL DEFAULT now(),
    feature       TEXT NOT NULL,   -- triage | investigate | rulegen
    model         TEXT NOT NULL,
    mock          BOOLEAN NOT NULL,
    cached        BOOLEAN NOT NULL DEFAULT FALSE,
    input_tokens  INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    latency_ms    INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS eval_runs (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts      TIMESTAMPTZ NOT NULL DEFAULT now(),
    dataset TEXT NOT NULL,
    result  JSONB NOT NULL
);

-- Sweep watermark and other pipeline state.
CREATE TABLE IF NOT EXISTS detect_state (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
